### PR TITLE
Now using voxel-engine 0.14.0

### PR DESCRIPTION
**Pull request by theoxylo**
Using voxel-highlight 0.0.8 with animated highlight transitions and newer raycast API

Also, I restored the old maxodgen.png as player.png since it looks a lot better! I hope nobody minds...

### CODE REVIEW

**Comment by theoxylo** [comment]
Oops, looks like I included too many commits. I will have to consult my reference manual now...

The end file states are good, but I don't think we want that merge commit in there. Sorry about that

**Comment by max-mapper** [comment]
I also should have put the most recent commit in this repo into a branch...

**Comment by theoxylo** [comment]
I fixed up this branch in my local repo, but I can't figure out how to push it...

Instead, I will submit a new pull request.

**Comment by theoxylo** [comment]
For future reference the --force option to git push would have done what I needed (overwritten the remote branch):

```
git push -f origin pull/adj
```

**Pull request closed without merging**
